.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
    - go install github.com/mbrukman/yaml2json/cmd/yaml2json@latest
    - export PATH=.go/bin/:$PATH
  cache:
    paths:
      - .go/pkg/mod/
      - .go/src/github.com/

stages:
  - validate


lint:
  stage: validate
  image: golang:1.17
  extends: .go-cache
  script:
    - '
      for F in ./OAS_Contracten/*.yaml; do
        json_file_path=$(echo $F | sed "s/.yaml/.json/");
        yaml2json $F > $json_file_path;
      done;
      git diff --text --exit-code HEAD || (echo "You should probably run make tojson" && exit 1)
      '