.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
    - go install github.com/mbrukman/yaml2json/cmd/yaml2json@v0.0.0-20221001214909-57b35dca0a2c
    - export PATH=.go/bin/:$PATH
  cache:
    paths:
      - .go/pkg/mod/
      - .go/src/github.com/

stages:
  - validate
  - deploy
  - package

lint:
  stage: validate
  image: golang:1.23
  extends: .go-cache
  script:
    - |
      for F in ./OAS_Contracten/*.yaml; do
        json_file_path=$(echo $F | sed "s/.yaml/.json/");
        yaml2json $F > $json_file_path;
      done;
      git diff --text --exit-code HEAD || (echo "You should probably run make tojson" && exit 1)

deploy_test:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
  environment:
    name: test
  script:
    - |
      echo "deployed"

deploy_accept:
  extends: deploy_test
  when: manual
  rules:
    - if: '$CI_COMMIT_TAG =~ /v\d+\.\d+\.\d+.*/'
  environment:
    name: accept

deploy_prod:
  extends: deploy_accept
  rules:
    - if: '$CI_COMMIT_TAG =~ /v\d+\.\d+\.\d+.*/'
  environment:
    name: prod

include:
  - local: ".ci/package-nuget.yml"