.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
    - go install github.com/mbrukman/yaml2json/cmd/yaml2json@latest
    - export PATH=.go/bin/:$PATH
  cache:
    paths:
      - .go/pkg/mod/
      - .go/src/github.com/

job-that-succeeds:
  stage: release
  script:
    - 'echo "It succeeded!"'
    - 'echo "Could make a job here to validate lint of yaml"'

tag:
  stage: release
  image: golang:1.17
  extends: .go-cache
  script:
    - '
      for F in ./OAS_Contracten/*.yaml; do
        json_file_path=$(echo $F | sed "s/.yaml/.json/");
        yaml2json $F > $json_file_path;
        
        json_file_name="$(basename -- $json_file_path)";
        curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file $json_file_path "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/json_oas_contracten/${CI_COMMIT_TAG}/$json_file_name";
      done;
      '
  rules:
    - if: '$CI_COMMIT_TAG =~ /\d+\.\d+\.\d+.*/'