openapi: 3.0.0
info:
  title: VUM API Werkgeverscontactmoment tussen VUM-UV en bemiddelaar
  description: Contract tbv interactie van bemiddelaars met VUM uitwisselingsvoorziening
    voor Werkgeverscontactmomenten
  contact:
    name: Helpdesk
    url: https://www.matchingsgegevens.nl
    email: programma-vum@ictu.nl
  version: 3.0.0
servers:
- url: https://test.vumdevelopment.nl/api/v3
  description: staging/test server
- url: https://accept.vumdevelopment.nl/api/v3
  description: acceptatie server
- url: https://prod.vumdevelopment.nl/api/v3
  description: productie server
paths:
  /werkgeverscontactmomenten/matches:
    post:
      summary: Zoekopdracht voor Werkgeverscontactmomenten
      description: Zoekopdracht om Werkgeverscontactmoment matches op te vragen
      operationId: MatchesWerkgeverscontactmomenten
      parameters:
      - $ref: '#/components/parameters/vum_bericht_versie'
      - $ref: '#/components/parameters/vum_from_party'
      - $ref: '#/components/parameters/vum_to_party'
      - $ref: '#/components/parameters/vum_via_party'
      - $ref: '#/components/parameters/api_version'
      requestBody:
        $ref: '#/components/requestBodies/WerkgeverscontactmomentMatchesRequest'
      responses:
        '200':
          description: OK
          headers:
            X-VUM-berichtVersie:
              $ref: '#/components/headers/vum_bericht_versie'
            X-VUM-fromParty:
              $ref: '#/components/headers/vum_from_party'
            X-VUM-toParty:
              $ref: '#/components/headers/vum_to_party'
            X-VUM-viaParty:
              $ref: '#/components/headers/vum_via_party'
            API-Version:
              $ref: '#/components/headers/api_version'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WerkgeverscontactmomentMatchesResponse'
        '400':
          description: Bad request
          headers:
            X-VUM-berichtVersie:
              $ref: '#/components/headers/vum_bericht_versie'
            X-VUM-fromParty:
              $ref: '#/components/headers/vum_from_party'
            X-VUM-toParty:
              $ref: '#/components/headers/vum_to_party'
            X-VUM-viaParty:
              $ref: '#/components/headers/vum_via_party'
            API-Version:
              $ref: '#/components/headers/api_version'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: not authorized
          headers:
            X-VUM-berichtVersie:
              $ref: '#/components/headers/vum_bericht_versie'
            X-VUM-fromParty:
              $ref: '#/components/headers/vum_from_party'
            X-VUM-toParty:
              $ref: '#/components/headers/vum_to_party'
            X-VUM-viaParty:
              $ref: '#/components/headers/vum_via_party'
            API-Version:
              $ref: '#/components/headers/api_version'
        '429':
          description: Too Many Requests
          headers:
            X-VUM-berichtVersie:
              $ref: '#/components/headers/vum_bericht_versie'
            X-VUM-fromParty:
              $ref: '#/components/headers/vum_from_party'
            X-VUM-toParty:
              $ref: '#/components/headers/vum_to_party'
            X-VUM-viaParty:
              $ref: '#/components/headers/vum_via_party'
            API-Version:
              $ref: '#/components/headers/api_version'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          headers:
            X-VUM-berichtVersie:
              $ref: '#/components/headers/vum_bericht_versie'
            X-VUM-fromParty:
              $ref: '#/components/headers/vum_from_party'
            X-VUM-toParty:
              $ref: '#/components/headers/vum_to_party'
            X-VUM-viaParty:
              $ref: '#/components/headers/vum_via_party'
            API-Version:
              $ref: '#/components/headers/api_version'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '503':
          description: Service Unavailable
          headers:
            X-VUM-berichtVersie:
              $ref: '#/components/headers/vum_bericht_versie'
            X-VUM-fromParty:
              $ref: '#/components/headers/vum_from_party'
            X-VUM-toParty:
              $ref: '#/components/headers/vum_to_party'
            X-VUM-viaParty:
              $ref: '#/components/headers/vum_via_party'
            API-Version:
              $ref: '#/components/headers/api_version'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
