openapi: 3.0.0
info:
  title: VUM API Vacatures tussen VUM-UV en bemiddelaar
  description: Contract tbv interactie van bemiddelaars met VUM uitwisselingsvoorziening
    voor Vacatures
  contact:
    name: Helpdesk
    url: https://www.matchingsgegevens.nl
    email: programma-vum@ictu.nl
  version: 3.0.0
servers:
- url: https://test.vumdevelopment.nl/api/v3
  description: staging/test server
- url: https://accept.vumdevelopment.nl/api/v3
  description: acceptatie server
- url: https://prod.vumdevelopment.nl/api/v3
  description: productie server
paths:
  /vacatures/matches:
    post:
      summary: Zoekopdracht voor Vacatures
      description: Zoekopdracht om Vacature matches op te vragen
      operationId: MatchesVacatures
      parameters:
      - $ref: '#/components/parameters/vum_bericht_versie'
      - $ref: '#/components/parameters/vum_from_party'
      - $ref: '#/components/parameters/vum_to_party'
      - $ref: '#/components/parameters/vum_via_party'
      - $ref: '#/components/parameters/api_version'
      requestBody:
        $ref: '#/components/requestBodies/VacatureMatchesRequest'
      responses:
        '200':
          description: OK
          headers:
            X-VUM-berichtVersie:
              $ref: '#/components/headers/vum_bericht_versie'
            X-VUM-fromParty:
              $ref: '#/components/headers/vum_from_party'
            X-VUM-toParty:
              $ref: '#/components/headers/vum_to_party'
            X-VUM-viaParty:
              $ref: '#/components/headers/vum_via_party'
            API-Version:
              $ref: '#/components/headers/api_version'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VacaturesMatchesResponse'
        '400':
          description: Bad request
          headers:
            X-VUM-berichtVersie:
              $ref: '#/components/headers/vum_bericht_versie'
            X-VUM-fromParty:
              $ref: '#/components/headers/vum_from_party'
            X-VUM-toParty:
              $ref: '#/components/headers/vum_to_party'
            X-VUM-viaParty:
              $ref: '#/components/headers/vum_via_party'
            API-Version:
              $ref: '#/components/headers/api_version'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: not authorized
          headers:
            X-VUM-berichtVersie:
              $ref: '#/components/headers/vum_bericht_versie'
            X-VUM-fromParty:
              $ref: '#/components/headers/vum_from_party'
            X-VUM-toParty:
              $ref: '#/components/headers/vum_to_party'
            X-VUM-viaParty:
              $ref: '#/components/headers/vum_via_party'
            API-Version:
              $ref: '#/components/headers/api_version'
        '429':
          description: Too Many Requests
          headers:
            X-VUM-berichtVersie:
              $ref: '#/components/headers/vum_bericht_versie'
            X-VUM-fromParty:
              $ref: '#/components/headers/vum_from_party'
            X-VUM-toParty:
              $ref: '#/components/headers/vum_to_party'
            X-VUM-viaParty:
              $ref: '#/components/headers/vum_via_party'
            API-Version:
              $ref: '#/components/headers/api_version'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          headers:
            X-VUM-berichtVersie:
              $ref: '#/components/headers/vum_bericht_versie'
            X-VUM-fromParty:
              $ref: '#/components/headers/vum_from_party'
            X-VUM-toParty:
              $ref: '#/components/headers/vum_to_party'
            X-VUM-viaParty:
              $ref: '#/components/headers/vum_via_party'
            API-Version:
              $ref: '#/components/headers/api_version'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '503':
          description: Service Unavailable
          headers:
            X-VUM-berichtVersie:
              $ref: '#/components/headers/vum_bericht_versie'
            X-VUM-fromParty:
              $ref: '#/components/headers/vum_from_party'
            X-VUM-toParty:
              $ref: '#/components/headers/vum_to_party'
            X-VUM-viaParty:
              $ref: '#/components/headers/vum_via_party'
            API-Version:
              $ref: '#/components/headers/api_version'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /vacatures/{vumID}:
    get:
      summary: Vraag volledige vacature op bij opgegeven vumID
      description: Vraag volledige vacature op bij een opgegeven vumID
      operationId: getVacature
      parameters:
      - name: vumID
        in: path
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/VumID'
      - $ref: '#/components/parameters/vum_bericht_versie'
      - $ref: '#/components/parameters/vum_from_party'
      - $ref: '#/components/parameters/vum_to_party'
      - $ref: '#/components/parameters/vum_via_party'
      - $ref: '#/components/parameters/api_version'
      responses:
        '200':
          description: OK
          headers:
            X-VUM-berichtVersie:
              $ref: '#/components/headers/vum_bericht_versie'
            X-VUM-fromParty:
              $ref: '#/components/headers/vum_from_party'
            X-VUM-toParty:
              $ref: '#/components/headers/vum_to_party'
            X-VUM-viaParty:
              $ref: '#/components/headers/vum_via_party'
            API-Version:
              $ref: '#/components/headers/api_version'
          content:
            application/json:
              schema:
                type: object
                properties:
                  bronID:
                    $ref: '#/components/schemas/String200'
                  vacature:
                    $ref: '#/components/schemas/Vacature'
        '400':
          description: Bad request
          headers:
            X-VUM-berichtVersie:
              $ref: '#/components/headers/vum_bericht_versie'
            X-VUM-fromParty:
              $ref: '#/components/headers/vum_from_party'
            X-VUM-toParty:
              $ref: '#/components/headers/vum_to_party'
            X-VUM-viaParty:
              $ref: '#/components/headers/vum_via_party'
            API-Version:
              $ref: '#/components/headers/api_version'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: not authorized
          headers:
            API-Version:
              $ref: '#/components/headers/api_version'
        '429':
          description: Too Many Requests, limiet is overschreden voor deze uitvraag
          headers:
            X-VUM-berichtVersie:
              $ref: '#/components/headers/vum_bericht_versie'
            X-VUM-fromParty:
              $ref: '#/components/headers/vum_from_party'
            X-VUM-toParty:
              $ref: '#/components/headers/vum_to_party'
            X-VUM-viaParty:
              $ref: '#/components/headers/vum_via_party'
            API-Version:
              $ref: '#/components/headers/api_version'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          headers:
            X-VUM-berichtVersie:
              $ref: '#/components/headers/vum_bericht_versie'
            X-VUM-fromParty:
              $ref: '#/components/headers/vum_from_party'
            X-VUM-toParty:
              $ref: '#/components/headers/vum_to_party'
            X-VUM-viaParty:
              $ref: '#/components/headers/vum_via_party'
            API-Version:
              $ref: '#/components/headers/api_version'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '503':
          description: Service Unavailable
          headers:
            X-VUM-berichtVersie:
              $ref: '#/components/headers/vum_bericht_versie'
            X-VUM-fromParty:
              $ref: '#/components/headers/vum_from_party'
            X-VUM-toParty:
              $ref: '#/components/headers/vum_to_party'
            X-VUM-viaParty:
              $ref: '#/components/headers/vum_via_party'
            API-Version:
              $ref: '#/components/headers/api_version'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
